### ISSUE TITLE
RuntimeError: mat1 dim 1 must match mat2 dim 0

### ISSUE THREAD

**Issue by Rachel-Yeah-Lee** [voidism/DiffCSE#17]
Hi, I am using your code to train DiffCSE with the model BERT-large and Roberta-large, and I use distilbert-base-uncased and distilroberta-base as the generator model. But I always encounter the runtimeError: mat1 dim 1 must match mat2 dim 0, which is fine when I use BERT-base or Roberta-base. Could you give me some advises, please? 
<img width="765" alt="擷取" src="https://user-images.githubusercontent.com/38121167/232202410-e0f6cd9e-9877-49dc-8858-c07176ee43bd.PNG">

**Comment by voidism** [comment]
Hi! I think that's because I set the hidden size to be 768 in train.py (L373 and L387): https://github.com/voidism/DiffCSE/blob/33b29a38f27ddb66f05c51daa050e868aa186bec/train.py#L373
https://github.com/voidism/DiffCSE/blob/33b29a38f27ddb66f05c51daa050e868aa186bec/train.py#L387
If you need to run bert-large or roberta-large, you can set them to be 1024. Thanks!

**Comment by Rachel-Yeah-Lee** [comment]
It works! Thanks a lot!
